import { FormControl} from '@angular/forms'
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class SearchPregnantForm {
    dateInpStart = new FormControl()
    dateInpEnd = new FormControl()
    patientId = new FormControl()
    familyName = new FormControl()
    firstName = new FormControl()
    thirdName = new FormControl()
    birthDateStart = new FormControl()
    birthDateEnd = new FormControl()
    regionReg = new FormControl()
    regionPreset = new FormControl()
    regionFact = new FormControl()
    factRegionPreset = new FormControl()
    country = new FormControl()
    dateRegOnStart = new FormControl()
    dateRegOnEnd = new FormControl()
    dateUnRegStart = new FormControl()
    dateUnRegEnd = new FormControl()
    stage = new FormControl()
    checkCourse = new FormControl()
    infectCourse = new FormControl()
    showIllnes = new FormControl()
    dateShowIllnesStart = new FormControl()
    dateShowIllnesEnd = new FormControl()
    transfAreaYNA = new FormControl()
    dateTransfAreaStart = new FormControl()
    dateTransfAreaEnd = new FormControl()
    frYNA = new FormControl()
    zavApoYNA = new FormControl()
    transfFederYNA = new FormControl()
    ufsinYNA = new FormControl()
    dateUfsinStart = new FormControl()
    dateUfsinEnd = new FormControl()
    
    pregCheck = new FormControl()
    pregMonthNo = new FormControl()
    birthType = new FormControl()
    medecineStartMonthNo = new FormControl()
    childBirthDateStart = new FormControl()
    childBirthDateEnd = new FormControl()
    childFamilyName = new FormControl()
    childFirstName = new FormControl()
    childThirdName = new FormControl()
    cardNo = new FormControl()
    phpSchema1 = new FormControl()
    phpSchema2 = new FormControl()
    phpSchema3 = new FormControl()
    medecineForSchema1 = new FormControl()
    medecineForSchema2 = new FormControl()
    medecineForSchema3 = new FormControl()
    art = new FormControl()
    materhome = new FormControl()
    aclDateStart = new FormControl()
    aclDateEnd = new FormControl()
    aclMcnCodeStart = new FormControl()
    aclMcnCodeEnd = new FormControl()


    selectInpDate = new FormControl()
    selectPatientId = new FormControl()
    selectFio = new FormControl()
    selectBirthDate = new FormControl()
    selectRegion = new FormControl()
    selectRegionFact = new FormControl()
    selectCountry = new FormControl()
    selectRegOnDate = new FormControl()
    selectStage = new FormControl()
    selectCheckCourse = new FormControl()
    selectInfectCourse = new FormControl()
    selectShowIllnes = new FormControl()
    selectTransfArea = new FormControl()
    selectFr = new FormControl()
    selectUfsin = new FormControl()

    selectPregCheck = new FormControl()
    selectPregMonthNo = new FormControl()
    selectBirthType = new FormControl()
    selectMedecineStartMonthNo = new FormControl()
    selectChildBirthDate = new FormControl()
    selectChildFio = new FormControl()
    selectCardNo = new FormControl()
    selectPhpSchema1 = new FormControl()
    selectPhpSchema2 = new FormControl()
    selectPhpSchema3 = new FormControl()
    selectMedecineForSchema1 = new FormControl()
    selectMedecineForSchema2 = new FormControl()
    selectMedecineForSchema3 = new FormControl()
    selectArt = new FormControl()
    selectAddr = new FormControl()
    selectMaterhome = new FormControl()
    selectAclDate = new FormControl()
    selectAclMcnCode = new FormControl()

    constructor(private listService: ListService) 
    {
      this.dateInpStart.setValue('')
      this.dateInpEnd.setValue('')
      this.patientId.setValue('')
      this.familyName.setValue('')
      this.firstName.setValue('')
      this.thirdName.setValue('')
      this.birthDateStart.setValue('')
      this.birthDateEnd.setValue('')
      this.regionReg.setValue(['Все'])
      this.regionReg.disable()
      this.regionPreset.setValue('Все')
      this.regionFact.setValue(['Все'])
      this.regionFact.disable()
      this.factRegionPreset.setValue('Все')
      this.country.setValue(['Все'])
      this.country.disable()
      this.dateRegOnStart.setValue('')
      this.dateRegOnEnd.setValue('')
      this.dateUnRegStart.setValue('')
      this.dateUnRegEnd.setValue('')
      this.stage.setValue(['Все'])
      this.stage.disable()
      this.checkCourse.setValue(['Все'])
      this.checkCourse.disable()
      this.infectCourse.setValue(['Все'])
      this.infectCourse.disable()
      this.showIllnes.setValue(['Все'])
      this.showIllnes.disable()
      this.dateShowIllnesStart.setValue('')
      this.dateShowIllnesEnd.setValue('')
      this.transfAreaYNA.setValue('Все')
      this.dateTransfAreaStart.setValue('')
      this.dateTransfAreaEnd.setValue('')
      this.frYNA.setValue('Все')
      this.zavApoYNA.setValue('Все')
      this.transfFederYNA.setValue('Все')
      this.ufsinYNA.setValue('Все')
      this.dateUfsinStart.setValue('')
      this.dateUfsinEnd.setValue('')

      this.pregCheck.setValue(['Все'])
      this.pregCheck.disable()
      this.pregMonthNo.setValue('')
      this.birthType.setValue(['Все'])
      this.birthType.disable()
      this.medecineStartMonthNo.setValue('')
      this.childBirthDateStart.setValue('')
      this.childBirthDateEnd.setValue('')
      this.childFamilyName.setValue('')
      this.childFirstName.setValue('')
      this.childThirdName.setValue('')
      this.cardNo.setValue('')
      this.phpSchema1.setValue(['Все'])
      this.phpSchema1.disable()
      this.phpSchema2.setValue(['Все'])
      this.phpSchema2.disable()
      this.phpSchema3.setValue(['Все'])
      this.phpSchema3.disable()
      this.medecineForSchema1.setValue(['Все'])
      this.medecineForSchema1.disable()
      this.medecineForSchema2.setValue(['Все'])
      this.medecineForSchema2.disable()
      this.medecineForSchema3.setValue(['Все'])
      this.medecineForSchema3.disable()
      this.art.setValue(['Все'])
      this.art.disable()
      this.materhome.setValue(['Все'])
      this.materhome.disable()
      this.aclDateStart.setValue('')
      this.aclDateEnd.setValue('')
      this.aclMcnCodeStart.setValue('')
      this.aclMcnCodeEnd.setValue('')

      this.selectInpDate.setValue(true)
      this.selectPatientId.setValue(true)
      this.selectFio.setValue(true)
      this.selectBirthDate.setValue(true)
      this.selectRegion.setValue(true)
      this.selectRegionFact.setValue(true)
      this.selectCountry.setValue(true)
      this.selectRegOnDate.setValue(true)
      this.selectStage.setValue(true)
      this.selectCheckCourse.setValue(true)
      this.selectInfectCourse.setValue(true)
      this.selectShowIllnes.setValue(true)
      this.selectTransfArea.setValue(true)
      this.selectFr.setValue(true)
      this.selectUfsin.setValue(true)

      this.selectPregCheck.setValue(true)
      this.selectPregMonthNo.setValue(true)
      this.selectBirthType.setValue(true)
      this.selectMedecineStartMonthNo.setValue(true)
      this.selectChildBirthDate.setValue(true)
      this.selectChildFio.setValue(true)
      this.selectCardNo.setValue(true)
      this.selectPhpSchema1.setValue(true)
      this.selectPhpSchema2.setValue(true)
      this.selectPhpSchema3.setValue(true)
      this.selectMedecineForSchema1.setValue(true)
      this.selectMedecineForSchema2.setValue(true)
      this.selectMedecineForSchema3.setValue(true)
      this.selectArt.setValue(true)
      this.selectAddr.setValue(true)
      this.selectMaterhome.setValue(true)
      this.selectAclDate.setValue(true)
      this.selectAclMcnCode.setValue(true)

      this.transfAreaYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.frYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.zavApoYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.transfFederYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.ufsinYNA.addAsyncValidators(InList.validateYNA(this.listService))
    }
}