import { FormControl} from '@angular/forms'
import { PatientCardChildModel } from 'src/app/_interfaces/patient-card-child.model';
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class PatientCardChildForm {
    patientId = new FormControl()
    patientFio = new FormControl()
    familyType = new FormControl()
    mId = new FormControl()
    mFio = new FormControl()
    fId = new FormControl()
    fFio = new FormControl()
    firstCheckDate = new FormControl()
    childPlace = new FormControl()
    breastMonth = new FormControl()
    childPhp = new FormControl()
    materHome = new FormControl()
    childDescr = new FormControl()
    growth = new FormControl()
    weight = new FormControl()
    forma309 = new FormControl()
    lastCareDate = new FormControl()
    communicationParentDate = new FormControl()
    callingDistrictSpecDate = new FormControl()
    refusalPhp = new FormControl()
    refusalResearch = new FormControl()
    refusalTherapy = new FormControl()

    constructor(data: PatientCardChildModel, private listService: ListService) 
    {
      this.patientId.setValue(data.patientId)
      this.patientId.disable()
      this.patientFio.setValue(data.patientFio)
      this.patientFio.disable()

      this.familyType.setValue(data.familyType)
      this.familyType.setAsyncValidators(InList.validateFamilyType(this.listService))
      this.mId.setValue(data.mId)
      this.mId.setAsyncValidators(InList.validatePatientCard(this.listService))
      this.mFio.setValue(data.mFio)
      this.mFio.disable()
      this.fId.setValue(data.fId)
      this.fId.setAsyncValidators(InList.validatePatientCard(this.listService))
      this.fFio.setValue(data.fFio)
      this.fFio.disable()
      this.firstCheckDate.setValue(data.firstCheckDate)
      this.childPlace.setValue(data.childPlace)
      this.childPlace.setAsyncValidators(InList.validateChildPlace(this.listService))
      this.breastMonth.setValue(data.breastMonth)
      this.childPhp.setValue(data.childPhp)
      this.childPhp.setAsyncValidators(InList.validateChildPhp(this.listService))
      this.materHome.setValue(data.materHome)
      this.materHome.setAsyncValidators(InList.validateMaterHome(this.listService))
      this.childDescr.setValue(data.childDescr)
      this.growth.setValue(data.growth)
      this.weight.setValue(data.weight)
      this.forma309.setValue(data.forma309)
      this.forma309.setAsyncValidators(InList.validateYn(this.listService))
      this.lastCareDate.setValue(data.lastCareDate)
      this.communicationParentDate.setValue(data.communicationParentDate)
      this.callingDistrictSpecDate.setValue(data.callingDistrictSpecDate)
      this.refusalPhp.setValue(data.refusalPhp)
      this.refusalResearch.setValue(data.refusalResearch)
      this.refusalTherapy.setValue(data.refusalTherapy)
    }
}