import { FormControl} from '@angular/forms'
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class SearchVisitForm {
    dateInpStart = new FormControl()
    dateInpEnd = new FormControl()
    patientId = new FormControl()
    familyName = new FormControl()
    firstName = new FormControl()
    thirdName = new FormControl()
    sex = new FormControl()
    birthDateStart = new FormControl()
    birthDateEnd = new FormControl()
    regionReg = new FormControl()
    regionPreset = new FormControl()
    regionFact = new FormControl()
    factRegionPreset = new FormControl()
    country = new FormControl()
    dateRegOnStart = new FormControl()
    dateRegOnEnd = new FormControl()
    dateUnRegStart = new FormControl()
    dateUnRegEnd = new FormControl()
    stage = new FormControl()
    checkCourse = new FormControl()
    infectCourse = new FormControl()
    showIllnes = new FormControl()
    dateShowIllnesStart = new FormControl()
    dateShowIllnesEnd = new FormControl()
    transfAreaYNA = new FormControl()
    dateTransfAreaStart = new FormControl()
    dateTransfAreaEnd = new FormControl()
    ufsinYNA = new FormControl()
    dateUfsinStart = new FormControl()
    dateUfsinEnd = new FormControl()
    frYNA = new FormControl()
    zavApoYNA = new FormControl()

    regDateStart = new FormControl()
    regDateEnd = new FormControl()
    checkDateStart = new FormControl()
    checkDateEnd = new FormControl()
    doctor = new FormControl()
    cardNo = new FormControl()
    art = new FormControl()
    regCheck = new FormControl()
    

    selectInpDate = new FormControl()
    selectPatientId = new FormControl()
    selectFio = new FormControl()
    selectSex = new FormControl()
    selectBirthDate = new FormControl()
    selectRegion = new FormControl()
    selectRegionFact = new FormControl()
    selectCountry = new FormControl()
    selectRegOnDate = new FormControl()
    selectStage = new FormControl()
    selectCheckCourse = new FormControl()
    selectInfectCourse = new FormControl()
    selectShowIllnes = new FormControl()
    selectTransfArea = new FormControl()
    selectFr = new FormControl()
    selectUfsin = new FormControl()
    selectRegDate = new FormControl()
    selectCheckDate = new FormControl()
    selectDoctor = new FormControl()
    selectCardNo = new FormControl()
    selectArt = new FormControl()
    selectAddr = new FormControl()
    selectRegCheck = new FormControl()

    constructor(private listService: ListService) 
    {
      this.dateInpStart.setValue('')
      this.dateInpEnd.setValue('')
      this.patientId.setValue('')
      this.familyName.setValue('')
      this.firstName.setValue('')
      this.thirdName.setValue('')
      this.sex.setValue('')
      this.birthDateStart.setValue('')
      this.birthDateEnd.setValue('')
      this.regionReg.setValue(['Все'])
      this.regionReg.disable()
      this.regionPreset.setValue('Все')
      this.regionFact.setValue(['Все'])
      this.regionFact.disable()
      this.factRegionPreset.setValue('Все')
      this.country.setValue(['Все'])
      this.country.disable()
      this.dateRegOnStart.setValue('')
      this.dateRegOnEnd.setValue('')
      this.dateUnRegStart.setValue('')
      this.dateUnRegEnd.setValue('')
      this.stage.setValue(['Все'])
      this.stage.disable()
      this.checkCourse.setValue(['Все'])
      this.checkCourse.disable()
      this.infectCourse.setValue(['Все'])
      this.infectCourse.disable()
      this.showIllnes.setValue(['Все'])
      this.showIllnes.disable()
      this.dateShowIllnesStart.setValue('')
      this.dateShowIllnesEnd.setValue('')
      this.transfAreaYNA.setValue('Все')
      this.dateTransfAreaStart.setValue('')
      this.dateTransfAreaEnd.setValue('')
      this.ufsinYNA.setValue('Все')
      this.dateUfsinStart.setValue('')
      this.dateUfsinEnd.setValue('')
      this.frYNA.setValue('Все')
      this.zavApoYNA.setValue('Все')

      this.regDateStart.setValue('')
      this.regDateEnd.setValue('')
      this.checkDateStart.setValue('')
      this.checkDateEnd.setValue('')
      this.doctor.setValue(['Все'])
      this.doctor.disable()
      this.cardNo.setValue('')
      this.art.setValue(['Все'])
      this.art.disable()
      this.regCheck.setValue('')


      this.selectInpDate.setValue(true)
      this.selectPatientId.setValue(true)
      this.selectFio.setValue(true)
      this.selectSex.setValue(true)
      this.selectBirthDate.setValue(true)
      this.selectRegion.setValue(true)
      this.selectRegionFact.setValue(true)
      this.selectCountry.setValue(true)
      this.selectRegOnDate.setValue(true)
      this.selectStage.setValue(true)
      this.selectCheckCourse.setValue(true)
      this.selectInfectCourse.setValue(true)
      this.selectShowIllnes.setValue(true)
      this.selectTransfArea.setValue(true)
      this.selectFr.setValue(true)
      this.selectUfsin.setValue(true)

      this.selectRegDate.setValue(true)
      this.selectCheckDate.setValue(true)
      this.selectDoctor.setValue(true)
      this.selectCardNo.setValue(true)
      this.selectArt.setValue(true)
      this.selectAddr.setValue(true)
      this.selectRegCheck.setValue(true)

      this.sex.addAsyncValidators(InList.validateSex(this.listService))
      this.transfAreaYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.frYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.zavApoYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.ufsinYNA.addAsyncValidators(InList.validateYNA(this.listService))
    }
}