 export interface  Covid{
     idCovid?: number
     patientId?: number
     periodDesDate?: Date
     positiveResCovidDate?: Date
     negativeResCovidDate?: Date
     hospDate?: Date
     dischargeDate?: Date
     outPatTreat?: string
     deathCovid?: string
     orit?: string
     oxygen?: string
     avl?: string
     arterHyper?: string
     deabetes?: string
     coronarySynd?: string
     hobl?: string
     bronhAstma?: string
     cancer?: string
     kidneyDes?: string
     outcomeHosp?: string
     clinVarCovid?: string
     severityCovid?: string
     covidMKB10Short?: string
     covidMKB10Long?: string
     tubercuosisShort?: string
     tubercuosisLong?: string
     pneumoniaShort?: string
     pneumoniaLong?: string
     typeAvl?: string
     commitment?: string
     comm?: string
 }