import { Course } from "./course.model"

export interface  SearchEpidListsModel{
   listSex?: string[]
   listRegion?: string[]
   listRegionPreset?: string[]
   listCountry?: string[]
   listCheckPlace?: string[]
   listRegOff?: string[]
   listStage?: string[]
   listCheckCourse?: Course[]
   listDieCourse?: string[]
   listDiePreset?: string[]
   listInfectCourse?: string[]
   listShowIllness?: string[]
   listResIb?: string[]
   listSelectBlot?: string[]
   listHospCourse?: string[]
   listAge?: string[]
   listArvt?: string[]
   listCodeMKB10?: string[]
   listAids12?: string[]
   listEducation?: string[]
   listFamilyStatus?: string[]
   listEmployment?: string[]
   listTrans?: string[]
   listPlaceCheck?: string[]
   listSituationDetected?: string[]
   listTransmisionMech?: string[]
   listVulnerableGroup?: string[]
   listCovidVac?: string[]
   listMkb10Covid?: string[]
   listContactType?: string[]
   listCallStatus?: string[]
   listYNA?: string[]
}