 export interface  SearchAnalyseModel{
    dateInpStart?: string 
    dateInpEnd?: string 
    patientId?: string 
    familyName?: string 
    firstName?: string 
    thirdName?: string 
    sex?: string 
    birthDateStart?: string 
    birthDateEnd?: string 
    regionReg?: string[] 
    regionPreset?: string 
    regionFact?: string[]
    factRegionPreset?: string 
    country?: string[]
    city?: string 
    location?: string 
    indx?: string 
    street?: string 
    home?: string 
    dateRegOnStart?: string 
    dateRegOnEnd?: string 
    dateUnRegStart?: string 
    dateUnRegEnd?: string 
    unRegCourse?: string 
    stage?: string[]
    dateDieStart?: string 
    dateDieEnd?: string 
    dateDieAidsStart?: string 
    dateDieAidsEnd?: string 
    dieCourse?: string[]
    diePreset?: string 
    checkCourse?: string[]
    infectCourse?: string[]
    showIllnes?: string[]
    dateShowIllnesStart?: string 
    dateShowIllnesEnd?: string 
    transfAreaYNA?: string 
    dateTransfAreaStart?: string 
    dateTransfAreaEnd?: string 
    frYNA?: string 
    zavApoYNA?: string 
    ibRes?: string 
    dateIbResStart?: string 
    dateIbResEnd?: string 
    ibNum?: string 
    dateInpIbStart?: string 
    dateInpIbEnd?: string 
    ibSelect?: string 
    ufsinYNA?: string 
    dateUfsinStart?: string 
    dateUfsinEnd?: string 

    dateVlStart?: string
    dateVlEnd?: string
    resVlStart?: string
    resVlEnd?: string
    dateIMStart?: string
    dateImEnd?: string
    resImCd3Start?: string
    resImCd3End?: string
    resImCd4Start?: string
    resImCd4End?: string
    resImCd8Start?: string
    resImCd8End?: string
    dateHepCIfaStart?: string
    dateHepCIfaEnd?: string
    dateHepCIfaVal?: string
    dateHepBIfaStart?: string
    dateHepBIfaEnd?: string
    dateHepBIfaVal?: string
    dateHepSyphIfaStart?: string
    dateHepSyphIfaEnd?: string
    dateHepSyphIfaVal?: string
    dateHepCStart?: string
    dateHepCEnd?: string
    dateHepBStart?: string
    dateHepBEnd?: string

    cardNo?: string 
    art?: string[]
    

    selectInpDate: boolean
    selectPatientId: boolean
    selectFio: boolean
    selectSex: boolean
    selectBirthDate: boolean
    selectRegion: boolean
    selectRegionFact: boolean
    selectCountry: boolean
    selectAddr: boolean
    selectRegOnDate: boolean
    selectStage: boolean
    selectDieDate: boolean
    selectDieCourse: boolean
    selectCheckCourse: boolean
    selectInfectCourse: boolean
    selectShowIllnes: boolean
    selectTransfArea: boolean
    selectFr: boolean
    selectIb: boolean
    selectUfsin: boolean
    selectCardNo: boolean
    selectArt: boolean
    selectVlDate: boolean
    selectVlRes: boolean
    selectImDate: boolean
    selectImCd3Res: boolean
    selectImCd4Res: boolean
    selectImCd8Res: boolean
    selectHepCIfa: boolean
    selectHepBIfa: boolean
    selectHepSyphIfa: boolean
    selectHepC: boolean
    selectHepB: boolean

    page: number
    excel: boolean
 }