 export interface  SearchMainInfModelLists{
    listSex?: string[]
    listRegion?: string[]
    listCountry?: string[]
    listInfectCourse?: string[]
    listCheckPlace?: string[]
    listStage?: string[]
    listCheckCourse?: string[]
    listDieCourse?: string[]
    listShowIllness?: string[]
    listResIb?: string[]
    listSelectBlot?: string[]
    listHospCourse?: string[]
    listAge?: string[]
    listArvt?: string[]
    listCodeMKB10?: string[]
    listYN?: string[]
    listYNA?: string[]
    listAids12?: string[]
    listChemop?: string[]
 }