 export interface SearchPregnantModel{
    dateInpStart?: string 
    dateInpEnd?: string 
    patientId?: string 
    familyName?: string 
    firstName?: string 
    thirdName?: string 
    birthDateStart?: string 
    birthDateEnd?: string 
    regionReg?: string[] 
    regionPreset?: string 
    regionFact?: string[]
    factRegionPreset?: string 
    country?: string[]
    dateRegOnStart?: string 
    dateRegOnEnd?: string 
    dateUnRegStart?: string 
    dateUnRegEnd?: string 
    stage?: string[]
    checkCourse?: string[]
    infectCourse?: string[]
    showIllnes?: string[]
    dateShowIllnesStart?: string 
    dateShowIllnesEnd?: string 
    transfAreaYNA?: string 
    dateTransfAreaStart?: string 
    dateTransfAreaEnd?: string 
    frYNA?: string 
    zavApoYNA?: string 
    ufsinYNA?: string 
    dateUfsinStart?: string 
    dateUfsinEnd?: string 

    pregCheck?: string[]
    pregMonthNo?: string 
    birthType?: string[]
    medecineStartMonthNo?: string 
    childBirthDateStart?: string 
    childBirthDateEnd?: string 
    childFamilyName?: string 
    childFirstName?: string 
    childThirdName?: string 
    cardNo?: string 
    phpSchema1?: string[]
    phpSchema2?: string[]
    phpSchema3?: string[]
    medecineForSchema1?: string[]
    medecineForSchema2?: string[]
    medecineForSchema3?: string[]
    art?: string[]
    materhome?: string[]
    aclDateStart?: string 
    aclDateEnd?: string 
    aclMcnCodeStart?: string 
    aclMcnCodeEnd?: string 

  
    selectInpDate: boolean
    selectPatientId: boolean
    selectFio: boolean
    selectBirthDate: boolean
    selectRegion: boolean
    selectRegionFact: boolean
    selectCountry: boolean
    selectRegOnDate: boolean
    selectStage: boolean
    selectCheckCourse: boolean
    selectInfectCourse: boolean
    selectShowIllnes: boolean
    selectTransfArea: boolean
    selectFr: boolean
    selectUfsin: boolean

    selectPregCheck: boolean
    selectPregMonthNo: boolean
    selectBirthType: boolean
    selectMedecineStartMonthNo: boolean
    selectChildBirthDate: boolean
    selectChildFio: boolean
    selectCardNo: boolean
    selectPhpSchema1: boolean
    selectPhpSchema2: boolean
    selectPhpSchema3: boolean
    selectMedecineForSchema1: boolean
    selectMedecineForSchema2: boolean
    selectMedecineForSchema3: boolean
    selectArt: boolean
    selectAddr: boolean
    selectMaterhome: boolean
    selectAclDate: boolean
    selectAclMcnCode: boolean

    page: number
    excel: boolean
 }