 export interface  SearchTreatmentModel{
    dateInpStart?: string 
    dateInpEnd?: string 
    patientId?: string 
    familyName?: string 
    firstName?: string 
    thirdName?: string 
    sex?: string 
    birthDateStart?: string 
    birthDateEnd?: string 
    regionReg?: string[] 
    regionPreset?: string 
    regionFact?: string[]
    factRegionPreset?: string 
    country?: string[]
    city?: string 
    location?: string 
    indx?: string 
    street?: string 
    home?: string 
    dateRegOnStart?: string 
    dateRegOnEnd?: string 
    dateUnRegStart?: string 
    dateUnRegEnd?: string 
    unRegCourse?: string 
    stage?: string[]
    dateDieStart?: string 
    dateDieEnd?: string 
    dateDieAidsStart?: string 
    dateDieAidsEnd?: string 
    dieCourse?: string[]
    diePreset?: string 
    checkCourse?: string[]
    infectCourse?: string[]
    showIllnes?: string[]
    dateShowIllnesStart?: string 
    dateShowIllnesEnd?: string 
    transfAreaYNA?: string 
    dateTransfAreaStart?: string 
    dateTransfAreaEnd?: string 
    frYNA?: string 
    zavApoYNA?: string 
    ibRes?: string 
    dateIbResStart?: string 
    dateIbResEnd?: string 
    ibNum?: string 
    dateInpIbStart?: string 
    dateInpIbEnd?: string 
    ibSelect?: string 
    ufsinYNA?: string 
    dateUfsinStart?: string 
    dateUfsinEnd?: string 
    invalid?: string[]
    correspIllnesses?: string[]
    dateCorrespIllnessesStart?: string 
    dateCorrespIllnessesEnd?: string 
    schema?: string[]
    schemaLast?: boolean 
    schemaMedecine?: string[]
    medecine?: string[]
    medecineGive?: string[]
    doctor?: string[]
    dateGiveStart?: string 
    dateGiveEnd?: string 
    schemaChange?: string[]
    cardNo?: string 
    dateSchemaStart?: string 
    dateSchemaEnd?: string 
    finSource?: string[]
    art?: string[]
    rangeTherapy?: string[]
    dateVlStart?: string
    dateVlEnd?: string
    resVlStart?: string
    resVlEnd?: string
    dateIMStart?: string
    dateImEnd?: string
    resImStart?: string
    resImEnd?: string
    

    selectInpDate: boolean
    selectPatientId: boolean
    selectFio: boolean
    selectSex: boolean
    selectBirthDate: boolean
    selectRegion: boolean
    selectRegionFact: boolean
    selectCountry: boolean
    selectAddr: boolean
    selectRegOnDate: boolean
    selectStage: boolean
    selectDieDate: boolean
    selectDieCourse: boolean
    selectCheckCourse: boolean
    selectInfectCourse: boolean
    selectShowIllnes: boolean
    selectTransfArea: boolean
    selectFr: boolean
    selectIb: boolean
    selectUfsin: boolean
    selectInvalid: boolean
    selectCorrespIllnesses: boolean
    selectSchema: boolean
    selectSchemaMedecine: boolean
    selectMedecine: boolean
    selectMedecineGive: boolean
    selectDoctor: boolean
    selectGiveDate: boolean
    selectSchemaChange: boolean
    selectCardNo: boolean
    selectSchemaDate: boolean
    selectFinSource: boolean
    selectArt: boolean
    selectRangeTherapy: boolean
    selectVlDate: boolean
    selectVlRes: boolean
    selectImDate: boolean
    selectImRes: boolean

    page: number
 }