import { FormControl} from '@angular/forms'
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class SearchAnalysisForm {
    dateInpStart = new FormControl()
    dateInpEnd = new FormControl()
    patientId = new FormControl()
    familyName = new FormControl()
    firstName = new FormControl()
    thirdName = new FormControl()
    sex = new FormControl()
    birthDateStart = new FormControl()
    birthDateEnd = new FormControl()
    regionReg = new FormControl()
    regionPreset = new FormControl()
    regionFact = new FormControl()
    factRegionPreset = new FormControl()
    country = new FormControl()
    city = new FormControl()
    location = new FormControl()
    indx = new FormControl()
    street = new FormControl()
    home = new FormControl()
    dateRegOnStart = new FormControl()
    dateRegOnEnd = new FormControl()
    dateUnRegStart = new FormControl()
    dateUnRegEnd = new FormControl()
    unRegCourse = new FormControl()
    dateDieStart = new FormControl()
    dateDieEnd = new FormControl()
    dateDieAidsStart = new FormControl()
    dateDieAidsEnd = new FormControl()
    dieCourse = new FormControl()
    diePreset = new FormControl()
    stage = new FormControl()
    checkCourse = new FormControl()
    infectCourse = new FormControl()
    showIllnes = new FormControl()
    dateShowIllnesStart = new FormControl()
    dateShowIllnesEnd = new FormControl()
    transfAreaYNA = new FormControl()
    dateTransfAreaStart = new FormControl()
    dateTransfAreaEnd = new FormControl()
    frYNA = new FormControl()
    zavApoYNA = new FormControl()
    ibRes = new FormControl()
    dateIbResStart = new FormControl()
    dateIbResEnd = new FormControl()
    ibNum = new FormControl()
    dateInpIbStart = new FormControl()
    dateInpIbEnd = new FormControl()
    ibSelect = new FormControl()
    ufsinYNA = new FormControl()
    dateUfsinStart = new FormControl()
    dateUfsinEnd = new FormControl()

    dateVlStart = new FormControl()
    dateVlEnd = new FormControl()
    resVlStart = new FormControl()
    resVlEnd = new FormControl()
    dateIMStart = new FormControl()
    dateImEnd = new FormControl()
    resImCd3Start = new FormControl()
    resImCd3End = new FormControl()
    resImCd4Start = new FormControl()
    resImCd4End = new FormControl()
    resImCd8Start = new FormControl()
    resImCd8End = new FormControl()
    dateHepCIfaStart = new FormControl()
    dateHepCIfaEnd = new FormControl()
    hepCIfaPNA = new FormControl()
    dateHepBIfaStart = new FormControl()
    dateHepBIfaEnd = new FormControl()
    hepBIfaPNA = new FormControl()
    dateHepSyphIfaStart = new FormControl()
    dateHepSyphIfaEnd = new FormControl()
    hepSyphIfaPNA = new FormControl()
    dateHepCStart = new FormControl()
    dateHepCEnd = new FormControl()
    dateHepBStart = new FormControl()
    dateHepBEnd = new FormControl()

    cardNo = new FormControl()
    art = new FormControl()


    selectInpDate = new FormControl()
    selectPatientId = new FormControl()
    selectFio = new FormControl()
    selectSex = new FormControl()
    selectBirthDate = new FormControl()
    selectRegion = new FormControl()
    selectRegionFact = new FormControl()
    selectCountry = new FormControl()
    selectAddr = new FormControl()
    selectRegOnDate = new FormControl()
    selectStage = new FormControl()
    selectDieDate = new FormControl()
    selectDieCourse = new FormControl()
    selectCheckCourse = new FormControl()
    selectInfectCourse = new FormControl()
    selectShowIllnes = new FormControl()
    selectTransfArea = new FormControl()
    selectFr = new FormControl()
    selectIb = new FormControl()
    selectUfsin = new FormControl()
    
    selectVlDate = new FormControl()
    selectVlRes = new FormControl()
    selectImDate = new FormControl()
    selectImCd3Res = new FormControl()
    selectImCd4Res = new FormControl()
    selectImCd8Res = new FormControl()
    selectHepCIfa = new FormControl()
    selectHepBIfa = new FormControl()
    selectHepSyphIfa = new FormControl()
    selectHepC = new FormControl()
    selectHepB = new FormControl()

    selectCardNo = new FormControl()
    selectArt = new FormControl()

    constructor(private listService: ListService) 
    {
      this.dateInpStart.setValue('')
      this.dateInpEnd.setValue('')
      this.patientId.setValue('')
      this.familyName.setValue('')
      this.firstName.setValue('')
      this.thirdName.setValue('')
      this.sex.setValue('')
      this.birthDateStart.setValue('')
      this.birthDateEnd.setValue('')
      this.regionReg.setValue(['Все'])
      this.regionReg.disable()
      this.regionPreset.setValue('Все')
      this.regionFact.setValue(['Все'])
      this.regionFact.disable()
      this.factRegionPreset.setValue('Все')
      this.country.setValue(['Все'])
      this.country.disable()
      this.city.setValue('')
      this.location.setValue('')
      this.indx.setValue('')
      this.street.setValue('')
      this.home.setValue('')
      this.dateRegOnStart.setValue('')
      this.dateRegOnEnd.setValue('')
      this.dateUnRegStart.setValue('')
      this.dateUnRegEnd.setValue('')
      this.unRegCourse.setValue('')
      this.dateDieStart.setValue('')
      this.dateDieEnd.setValue('')
      this.dateDieAidsStart.setValue('')
      this.dateDieAidsEnd.setValue('')
      this.dieCourse.setValue(['Все'])
      this.dieCourse.disable()
      this.diePreset.setValue('Все')
      this.stage.setValue(['Все'])
      this.stage.disable()
      this.checkCourse.setValue(['Все'])
      this.checkCourse.disable()
      this.infectCourse.setValue(['Все'])
      this.infectCourse.disable()
      this.showIllnes.setValue(['Все'])
      this.showIllnes.disable()
      this.dateShowIllnesStart.setValue('')
      this.dateShowIllnesEnd.setValue('')
      this.transfAreaYNA.setValue('Все')
      this.dateTransfAreaStart.setValue('')
      this.dateTransfAreaEnd.setValue('')
      this.frYNA.setValue('Все')
      this.zavApoYNA.setValue('Все')
      this.ibRes.setValue('')
      this.dateIbResStart.setValue('')
      this.dateIbResEnd.setValue('')
      this.ibNum.setValue('')
      this.dateInpIbStart.setValue('')
      this.dateInpIbEnd.setValue('')
      this.ibSelect.setValue('Все')
      this.ufsinYNA.setValue('Все')
      this.dateUfsinStart.setValue('')
      this.dateUfsinEnd.setValue('')

      this.dateVlStart.setValue('')
      this.dateVlEnd.setValue('')
      this.resVlStart.setValue('')
      this.resVlEnd.setValue('')
      this.dateIMStart.setValue('')
      this.dateImEnd.setValue('')
      this.resImCd3Start.setValue('')
      this.resImCd3End.setValue('')
      this.resImCd4Start.setValue('')
      this.resImCd4End.setValue('')
      this.resImCd8Start.setValue('')
      this.resImCd8End.setValue('')

      this.dateHepCIfaStart.setValue('')
      this.dateHepCIfaEnd.setValue('')
      this.hepCIfaPNA.setValue('Все')
      this.dateHepBIfaStart.setValue('')
      this.dateHepBIfaEnd.setValue('')
      this.hepBIfaPNA.setValue('Все')
      this.dateHepSyphIfaStart.setValue('')
      this.dateHepSyphIfaEnd.setValue('')
      this.hepSyphIfaPNA.setValue('Все')
      this.dateHepCStart.setValue('')
      this.dateHepCEnd.setValue('')
      this.dateHepBStart.setValue('')
      this.dateHepBEnd.setValue('')

      this.cardNo.setValue('')
      this.art.setValue(['Все'])
      this.art.disable()

      this.selectInpDate.setValue(true)
      this.selectPatientId.setValue(true)
      this.selectFio.setValue(true)
      this.selectSex.setValue(true)
      this.selectBirthDate.setValue(true)
      this.selectRegion.setValue(true)
      this.selectRegionFact.setValue(true)
      this.selectCountry.setValue(true)
      this.selectAddr.setValue(true)
      this.selectRegOnDate.setValue(true)
      this.selectStage.setValue(true)
      this.selectDieDate.setValue(true)
      this.selectDieCourse.setValue(true)
      this.selectCheckCourse.setValue(true)
      this.selectInfectCourse.setValue(true)
      this.selectShowIllnes.setValue(true)
      this.selectTransfArea.setValue(true)
      this.selectFr.setValue(true)
      this.selectIb.setValue(true)
      this.selectUfsin.setValue(true)

      this.selectVlDate.setValue(true)
      this.selectVlRes.setValue(true)
      this.selectImDate.setValue(true)
      this.selectImCd3Res.setValue(true)
      this.selectImCd4Res.setValue(true)
      this.selectImCd8Res.setValue(true)
      this.selectHepCIfa.setValue(true)
      this.selectHepBIfa.setValue(true)
      this.selectHepSyphIfa.setValue(true)
      this.selectHepC.setValue(true)
      this.selectHepB.setValue(true)
      this.selectCardNo.setValue(true)
      this.selectArt.setValue(true)


      this.transfAreaYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.frYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.zavApoYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.ufsinYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.hepCIfaPNA.addAsyncValidators(InList.validatePNA(this.listService))
      this.hepBIfaPNA.addAsyncValidators(InList.validatePNA(this.listService))
      this.hepSyphIfaPNA.addAsyncValidators(InList.validatePNA(this.listService))
    }
}