import { FormControl} from '@angular/forms'
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class SearchEpidForm {
  dateInpStart = new FormControl()
  dateInpEnd = new FormControl()
  patientId = new FormControl()
  familyName = new FormControl()
  firstName = new FormControl()
  thirdName = new FormControl()
  sex = new FormControl()
  birthDateStart = new FormControl()
  birthDateEnd = new FormControl()
  regionReg = new FormControl()
  regionPreset = new FormControl()
  regionFact = new FormControl()
  factRegionPreset = new FormControl()
  country = new FormControl()
  city = new FormControl()
  location = new FormControl()
  indx = new FormControl()
  street = new FormControl()
  home = new FormControl()
  dateRegOnStart = new FormControl()
  dateRegOnEnd = new FormControl()
  dateUnRegStart = new FormControl()
  dateUnRegEnd = new FormControl()
  unRegCourse = new FormControl()
  blotCheckPlace = new FormControl()
  stage = new FormControl()
  dateDieStart = new FormControl()
  dateDieEnd = new FormControl()
  dateDieAidsStart = new FormControl()
  dateDieAidsEnd = new FormControl()
  checkCourse = new FormControl()
  dieCourse = new FormControl()
  diePreset = new FormControl()
  infectCourse = new FormControl()
  showIllnes = new FormControl()
  dateShowIllnesStart = new FormControl()
  dateShowIllnesEnd = new FormControl()
  ibRes = new FormControl()
  dateIbResStart = new FormControl()
  dateIbResEnd = new FormControl()
  ibNum = new FormControl()
  dateInpIbStart = new FormControl()
  dateInpIbEnd = new FormControl()
  ibSelect = new FormControl()
  hospCourse = new FormControl()
  age = new FormControl()
  cardNo = new FormControl()
  art = new FormControl()
  mkb10 = new FormControl()
  transfAreaYNA = new FormControl()
  dateTransfAreaStart = new FormControl()
  dateTransfAreaEnd = new FormControl()
  frYNA = new FormControl()
  zavApoYNA = new FormControl()
  transfFederYNA = new FormControl()
  dateTransfFederStart = new FormControl()
  dateTransfFederEnd = new FormControl()
  ufsinYNA = new FormControl()
  dateUfsinStart = new FormControl()
  dateUfsinEnd = new FormControl()
  aids12 = new FormControl()

  dtMailRegStart = new FormControl()
  dtMailRegEnd = new FormControl()
  education = new FormControl()
  familyStatus = new FormControl()
  employment = new FormControl()
  trans = new FormControl()
  placeCheck = new FormControl()
  situationDetect = new FormControl()
  transmisionMech = new FormControl()
  vulnerableGroup = new FormControl()
  vacName = new FormControl()
  vacDateStart = new FormControl()
  vacDateEnd = new FormControl()
  covidMkb10 = new FormControl()
  covidDateStart = new FormControl()
  covidDateEnd = new FormControl()
  chemsexYNA = new FormControl()
  chemsexContactType = new FormControl()
  pavInjYNA = new FormControl()
  pavInjDateStart = new FormControl()
  pavInjDateEnd = new FormControl()
  pavNotInjYNA = new FormControl()
  pavNotInjDateStart = new FormControl()
  pavNotInjDateEnd = new FormControl()
  timeInfectDateStart = new FormControl()
  timeInfectDateEnd = new FormControl()


  selectInpDate = new FormControl()
  selectPatientId = new FormControl()
  selectFio = new FormControl()
  selectSex = new FormControl()
  selectBirthDate = new FormControl()
  selectRegion = new FormControl()
  selectRegionFact = new FormControl()
  selectCountry = new FormControl()
  selectAddr = new FormControl()
  selectRegOnDate = new FormControl()
  selectBlotCheckPlace = new FormControl()
  selectStage = new FormControl()
  selectDieDate = new FormControl()
  selectCheckCourse = new FormControl()
  selectDieCourse = new FormControl()
  selectInfectCourse = new FormControl()
  selectShowIllnes = new FormControl()
  selectIb = new FormControl()
  selectHospCourse = new FormControl()
  selectAge = new FormControl()
  selectCardNo = new FormControl()
  selectArt = new FormControl()
  selectMkb10 = new FormControl()
  selectTransfArea = new FormControl()
  selectFr = new FormControl()
  selectTransfFeder = new FormControl()
  selectUfsin = new FormControl()
  selectAids12 = new FormControl()
  
  selectDtMailReg = new FormControl()
  selectEdu = new FormControl()
  selectFamilyStatus = new FormControl()
  selectEmployment = new FormControl()
  selectTrans = new FormControl()
  selectPlaceCheck = new FormControl()
  selectSituationDetect = new FormControl()
  selectTransmisionMech = new FormControl()
  selectVulnerableGroup = new FormControl()
  selectCovidVac = new FormControl()
  selectCovid = new FormControl()
  selectChemsex = new FormControl()
  selectPavInj = new FormControl()
  selectPavNotInj = new FormControl()
  selectTimeInfect = new FormControl()

  constructor(private listService: ListService) 
  {
    this.dateInpStart.setValue('')
    this.dateInpEnd.setValue('')
    this.patientId.setValue('')
    this.familyName.setValue('')
    this.firstName.setValue('')
    this.thirdName.setValue('')
    this.sex.setValue('')
    this.birthDateStart.setValue('')
    this.birthDateEnd.setValue('')
    this.regionReg.setValue(['Все'])
    this.regionReg.disable()
    this.regionPreset.setValue('Все')
    this.regionFact.setValue(['Все'])
    this.regionFact.disable()
    this.factRegionPreset.setValue('Все')
    this.country.setValue(['Все'])
    this.country.disable()
    this.city.setValue('')
    this.location.setValue('')
    this.indx.setValue('')
    this.street.setValue('')
    this.home.setValue('')
    this.dateRegOnStart.setValue('')
    this.dateRegOnEnd.setValue('')
    this.dateUnRegStart.setValue('')
    this.dateUnRegEnd.setValue('')
    this.unRegCourse.setValue('')
    this.blotCheckPlace.setValue(['Все'])
    this.blotCheckPlace.disable()
    this.stage.setValue(['Все'])
    this.stage.disable()
    this.dateDieStart.setValue('')
    this.dateDieEnd.setValue('')
    this.dateDieAidsStart.setValue('')
    this.dateDieAidsEnd.setValue('')
    this.checkCourse.setValue(['Все'])
    this.checkCourse.disable()
    this.dieCourse.setValue(['Все'])
    this.dieCourse.disable()
    this.diePreset.setValue('Все')
    this.infectCourse.setValue(['Все'])
    this.infectCourse.disable()
    this.showIllnes.setValue(['Все'])
    this.showIllnes.disable()
    this.dateShowIllnesStart.setValue('')
    this.dateShowIllnesEnd.setValue('')
    this.ibRes.setValue('')
    this.dateIbResStart.setValue('')
    this.dateIbResEnd.setValue('')
    this.ibNum.setValue('')
    this.dateInpIbStart.setValue('')
    this.dateInpIbEnd.setValue('')
    this.ibSelect.setValue('Все')
    this.hospCourse.setValue(['Все'])
    this.hospCourse.disable()
    this.age.setValue(['Все'])
    this.age.disable()
    this.cardNo.setValue('')
    this.art.setValue(['Все'])
    this.art.disable()
    this.mkb10.setValue(['Все'])
    this.mkb10.disable()
    this.transfAreaYNA.setValue('')
    this.dateTransfAreaStart.setValue('')
    this.dateTransfAreaEnd.setValue('')
    this.frYNA.setValue('Все')
    this.zavApoYNA.setValue('Все')
    this.transfAreaYNA.setValue('Все')
    this.transfFederYNA.setValue('Все')
    this.dateTransfFederStart.setValue('')
    this.dateTransfFederEnd.setValue('')
    this.ufsinYNA.setValue('Все')
    this.dateUfsinStart.setValue('')
    this.dateUfsinEnd.setValue('')
    this.aids12.setValue('')

    this.dtMailRegStart.setValue('')
    this.dtMailRegEnd.setValue('')
    this.education.setValue(['Все'])
    this.education.disable()
    this.familyStatus.setValue(['Все'])
    this.familyStatus.disable()
    this.employment.setValue(['Все'])
    this.employment.disable()
    this.trans.setValue(['Все'])
    this.trans.disable()
    this.placeCheck.setValue(['Все'])
    this.placeCheck.disable()
    this.situationDetect.setValue(['Все'])
    this.situationDetect.disable()
    this.transmisionMech.setValue(['Все'])
    this.transmisionMech.disable()
    this.vulnerableGroup.setValue(['Все'])
    this.vulnerableGroup.disable()
    this.vacName.setValue('')
    this.vacDateStart.setValue('')
    this.vacDateEnd.setValue('')
    this.covidMkb10.setValue('')
    this.covidDateStart.setValue('')
    this.covidDateEnd.setValue('')
    this.chemsexYNA.setValue('Все')
    this.chemsexContactType.setValue('')
    this.pavInjYNA.setValue('Все')
    this.pavInjDateStart.setValue('')
    this.pavInjDateEnd.setValue('')
    this.pavNotInjYNA.setValue('Все')
    this.pavNotInjDateStart.setValue('')
    this.pavNotInjDateEnd.setValue('')
    this.timeInfectDateStart.setValue('')
    this.timeInfectDateEnd.setValue('')

    this.selectInpDate.setValue(true)
    this.selectPatientId.setValue(true)
    this.selectFio.setValue(true)
    this.selectSex.setValue(true)
    this.selectBirthDate.setValue(true)
    this.selectRegion.setValue(true)
    this.selectRegionFact.setValue(true)
    this.selectCountry.setValue(true)
    this.selectAddr.setValue(true)
    this.selectRegOnDate.setValue(true)
    this.selectBlotCheckPlace.setValue(true)
    this.selectStage.setValue(true)
    this.selectDieDate.setValue(true)
    this.selectCheckCourse.setValue(true)
    this.selectDieCourse.setValue(true)
    this.selectInfectCourse.setValue(true)
    this.selectShowIllnes.setValue(true)
    this.selectIb.setValue(true)
    this.selectHospCourse.setValue(true)
    this.selectAge.setValue(true)
    this.selectCardNo.setValue(true)
    this.selectArt.setValue(true)
    this.selectMkb10.setValue(true)
    this.selectTransfArea.setValue(true)
    this.selectFr.setValue(true)
    this.selectTransfFeder.setValue(true)
    this.selectUfsin.setValue(true)
    this.selectAids12.setValue(true)
  
    this.selectDtMailReg.setValue(true)
    this.selectEdu.setValue(true)
    this.selectFamilyStatus.setValue(true)
    this.selectEmployment.setValue(true)
    this.selectTrans.setValue(true)
    this.selectPlaceCheck.setValue(true)
    this.selectSituationDetect.setValue(true)
    this.selectTransmisionMech.setValue(true)
    this.selectVulnerableGroup.setValue(true)
    this.selectCovidVac.setValue(true)
    this.selectCovid.setValue(true)
    this.selectChemsex.setValue(true)
    this.selectPavInj.setValue(true)
    this.selectPavNotInj.setValue(true)
    this.selectTimeInfect.setValue(true)

    this.sex.addAsyncValidators(InList.validateSex(this.listService))
    this.unRegCourse.addAsyncValidators(InList.validateInfectCourseLong(this.listService))
    this.ibRes.addAsyncValidators(InList.validateIbResult(this.listService))
    this.transfAreaYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.frYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.zavApoYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.transfFederYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.ufsinYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.aids12.addAsyncValidators(InList.validateAids12(this.listService))
    this.chemsexYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.pavInjYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.pavNotInjYNA.addAsyncValidators(InList.validateYNA(this.listService))
    this.covidMkb10.addAsyncValidators(InList.validateMkb10Covid(this.listService))
    this.chemsexContactType.addAsyncValidators(InList.validateInfectCourseLong(this.listService))
  }
}