import { FormControl} from '@angular/forms'
import { ListService } from 'src/app/services/list.service';
import { InList } from 'src/app/validators/in-lst';

export class SearchNonresidentForm {
    dateInpStart = new FormControl()
    dateInpEnd = new FormControl()
    patientId = new FormControl()
    familyName = new FormControl()
    firstName = new FormControl()
    thirdName = new FormControl()
    sex = new FormControl()
    birthDateStart = new FormControl()
    birthDateEnd = new FormControl()
    regionReg = new FormControl()
    regionPreset = new FormControl()
    regionFact = new FormControl()
    factRegionPreset = new FormControl()
    country = new FormControl()
    dateRegOnStart = new FormControl()
    dateRegOnEnd = new FormControl()
    dateUnRegStart = new FormControl()
    dateUnRegEnd = new FormControl()
    stage = new FormControl()
    stageDateStart = new FormControl()
    stageDateEnd = new FormControl()
    checkCourse = new FormControl()
    infectCourse = new FormControl()
    showIllnes = new FormControl()
    dateShowIllnesStart = new FormControl()
    dateShowIllnesEnd = new FormControl()
    transfAreaYNA = new FormControl()
    dateTransfAreaStart = new FormControl()
    dateTransfAreaEnd = new FormControl()
    ufsinYNA = new FormControl()
    dateUfsinStart = new FormControl()
    dateUfsinEnd = new FormControl()
    frYNA = new FormControl()
    zavApoYNA = new FormControl()
    
    dateDiagnosisStart = new FormControl()
    dateDiagnosisEnd = new FormControl()
    placeDiagnosis = new FormControl()
    dateRegistrationYNA = new FormControl()
    dateRegistrationStart = new FormControl()
    dateRegistrationEnd = new FormControl()
    dateDepartureYNA = new FormControl()
    dateDepartureStart = new FormControl()
    dateDepartureEnd = new FormControl()

    
    selectInpDate = new FormControl()
    selectPatientId = new FormControl()
    selectFio = new FormControl()
    selectSex = new FormControl()
    selectBirthDate = new FormControl()
    selectRegion = new FormControl()
    selectRegionFact = new FormControl()
    selectCountry = new FormControl()
    selectRegOnDate = new FormControl()
    selectStage = new FormControl()
    selectCheckCourse = new FormControl()
    selectInfectCourse = new FormControl()
    selectShowIllnes = new FormControl()
    selectTransfArea = new FormControl()
    selectFr = new FormControl()
    selectUfsin = new FormControl()
    
    selectDateDiagnosis = new FormControl()
    selectPlaceDiagnosis = new FormControl()
    selectDateRegistration = new FormControl()
    selectDateDeparture = new FormControl()
    selectAddr = new FormControl()

    constructor(private listService: ListService) 
    {
      this.dateInpStart.setValue('')
      this.dateInpEnd.setValue('')
      this.patientId.setValue('')
      this.familyName.setValue('')
      this.firstName.setValue('')
      this.thirdName.setValue('')
      this.sex.setValue('')
      this.birthDateStart.setValue('')
      this.birthDateEnd.setValue('')
      this.regionReg.setValue(['Все'])
      this.regionReg.disable()
      this.regionPreset.setValue('Все')
      this.regionFact.setValue(['Все'])
      this.regionFact.disable()
      this.factRegionPreset.setValue('Все')
      this.country.setValue(['Все'])
      this.country.disable()
      this.dateRegOnStart.setValue('')
      this.dateRegOnEnd.setValue('')
      this.dateUnRegStart.setValue('')
      this.dateUnRegEnd.setValue('')
      this.stage.setValue(['Все'])
      this.stage.disable()
      this.stageDateStart.setValue('')
      this.stageDateEnd.setValue('')
      this.checkCourse.setValue(['Все'])
      this.checkCourse.disable()
      this.infectCourse.setValue(['Все'])
      this.infectCourse.disable()
      this.showIllnes.setValue(['Все'])
      this.showIllnes.disable()
      this.dateShowIllnesStart.setValue('')
      this.dateShowIllnesEnd.setValue('')
      this.transfAreaYNA.setValue('Все')
      this.dateTransfAreaStart.setValue('')
      this.dateTransfAreaEnd.setValue('')
      this.ufsinYNA.setValue('Все')
      this.dateUfsinStart.setValue('')
      this.dateUfsinEnd.setValue('')
      this.frYNA.setValue('Все')
      this.zavApoYNA.setValue('Все')
      
    
      this.dateDiagnosisStart.setValue('')
      this.dateDiagnosisEnd.setValue('')
      this.placeDiagnosis.setValue(['Все'])
      this.placeDiagnosis.disable()
      this.dateRegistrationYNA.setValue('Все')
      this.dateRegistrationStart.setValue('')
      this.dateRegistrationEnd.setValue('')
      this.dateDepartureYNA.setValue('Все')
      this.dateDepartureStart.setValue('')
      this.dateDepartureEnd.setValue('')


      this.selectInpDate.setValue(true)
      this.selectPatientId.setValue(true)
      this.selectFio.setValue(true)
      this.selectSex.setValue(true)
      this.selectBirthDate.setValue(true)
      this.selectRegion.setValue(true)
      this.selectRegionFact.setValue(true)
      this.selectCountry.setValue(true)
      this.selectRegOnDate.setValue(true)
      this.selectStage.setValue(true)
      this.selectCheckCourse.setValue(true)
      this.selectInfectCourse.setValue(true)
      this.selectShowIllnes.setValue(true)
      this.selectTransfArea.setValue(true)
      this.selectFr.setValue(true)
      this.selectUfsin.setValue(true)
    
      this.selectDateDiagnosis.setValue(true)
      this.selectPlaceDiagnosis.setValue(true)
      this.selectDateRegistration.setValue(true)
      this.selectDateDeparture.setValue(true)
      this.selectAddr.setValue(true)


      this.sex.addAsyncValidators(InList.validateSex(this.listService))
      this.transfAreaYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.frYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.zavApoYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.ufsinYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.dateRegistrationYNA.addAsyncValidators(InList.validateYNA(this.listService))
      this.dateDepartureYNA.addAsyncValidators(InList.validateYNA(this.listService))
    }
}